version: '2'
services:
  # M3dev container
  fusio:
    image: intigration/dev
    environment:
      FUSIO_PROJECT_KEY: "42eec18ffdbffc9fda6110dcc705d6ce"
      FUSIO_HOST: "0.0.0.0"
      FUSIO_URL: "http://0.0.0.0"
      FUSIO_APPS_URL: "http://0.0.0.0/apps"
      FUSIO_ENV: "prod"
      FUSIO_DB_NAME: "m3db"
      FUSIO_DB_USER: "dbuser"
      FUSIO_DB_PW: "dbpassword"
      FUSIO_DB_HOST: "mysql_fusio"
      FUSIO_BACKEND_USER: "demo"
      FUSIO_BACKEND_EMAIL: "demo@fusio-project.org"
      FUSIO_BACKEND_PW: "75dafcb12c4f"
      FUSIO_VERSION: "master"
      PROVIDER_FACEBOOK_KEY: ""
      PROVIDER_FACEBOOK_SECRET: ""
      PROVIDER_GOOGLE_KEY: ""
      PROVIDER_GOOGLE_SECRET: ""
      PROVIDER_GITHUB_KEY: ""
      PROVIDER_GITHUB_SECRET: ""
      RECAPTCHA_KEY: ""
      RECAPTCHA_SECRET: ""
    links:
      - mysql_fusio
    ports:
      - "80:80"
    volumes:
      - ./apps:/var/www/html/fusio/apps
      - ./public:/var/www/html/fusio/public

  # Fusio system database
  mysql_fusio:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "7f3e5186032a"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpassword"
      MYSQL_DATABASE: "m3db"
    volumes:
      - ./db:/var/lib/mysql
